### ISSUE TITLE
Request's URL isn't correct when using port forwarding

### ISSUE THREAD

**Issue by zYg-sys** [edwig/Marlin#15]
Suppose our server is running behind a router,
the service is accessed via a router by the outside.

The service program is listening on port 80,
and mapped to port 8080 by the router to the outside.

When a request comes in,
the client's request URL would be http://domain.name:8080/path,
but the cooked URL in PHTTP_REQUEST is http://domain.name/path,
which uses the default 80 port that is currently listening on.

The problem is when we build some URLs to send to the client,
we cannot find the correct 8080 port in HTTPMessage or other places.

I think we should consider the Host header when parsing the request URL,
instead of trust the Cooked URL in PHTTP_REQUEST.

**Comment by edwig** [comment]
Hmmm……

That depends on what you want to use it for.
It may be better to isolate the internal knowledge of the server completely from things like routers, load-balancers or proxies, and not knowing anything about them. 
You might get hooked-up in all sorts of dependencies.

And if you really want to know, you can always get the host header from the HTTPMessage,
or other headers like the ["X-Forwarded-For"](https://en.wikipedia.org/wiki/X-Forwarded-For) header for this purpose.

For now, I would **not** consider messing up the URL as given by the Microsoft framework….
If I am listening on port 80, that's what I want to get from the operating system....

**Comment by zYg-sys** [comment]
That's OK for me.

I'll use request headers to construct the response.

Thanks.
