### ISSUE TITLE
It is recommended to implement base64 functionality using the Windows API.

### ISSUE THREAD

**Issue by williamlzw** [edwig/Marlin#20]
wstring Base64Encode(std::vector<UCHAR> data, DWORD type)
{
    DWORD flags = CRYPT_STRING_NOCRLF;
    if (type == 0)
    {
        flags = CRYPT_STRING_BASE64 | CRYPT_STRING_NOCRLF;
    }
    else if (type == 1)
    {
        flags = CRYPT_STRING_NOCRLF;
    }
    DWORD retLen = 0;
    CryptBinaryToStringW(data.data(), data.size(), flags, NULL, &retLen);
    std::wstring retStr;
    retStr.resize(retLen);
    CryptBinaryToStringW(data.data(), data.size(), flags, (LPWSTR)retStr.c_str(), &retLen);
    return retStr.substr(0, retLen);
}

std::vector<UCHAR> Base64Decode(wstring str)
{
    DWORD len = str.size();
    DWORD retLen = 3 * len / 4;
    std::vector<UCHAR> ret;
    ret.resize(retLen);
    CryptStringToBinaryW(str.c_str(), len, CRYPT_STRING_BASE64_ANY, ret.data(), &retLen, NULL, NULL);
    return ret;
}

**Comment by edwig** [comment]
Thank you for the hint. But....
This method was not used, because to do it properly, you must call it twice (once for calculating the length and once for doing the conversion a SECOND time). The current implementation did already exist and is sufficently fast.
