### ISSUE TITLE
It is recommended to use Bcrypt to achieve encryption and decryption function, the speed is dozens of times faster than crypt.

### ISSUE THREAD

**Issue by williamlzw** [edwig/Marlin#21]
wstring
Crypto::Digest(wstring& p_buffer, wstring& p_password)
{
	AutoCritSec lock(&m_lock);
	BCRYPT_ALG_HANDLE hAlgorithm;
	BCryptOpenAlgorithmProvider(&hAlgorithm, L"MD5", NULL, BCRYPT_HASH_REUSABLE_FLAG);
	UCHAR HashLength;
	ULONG DigestLength;
	BCryptGetProperty(hAlgorithm, L"HashDigestLength", &HashLength, 4, &DigestLength, NULL);
	BCRYPT_HASH_HANDLE HashHandle;
	BCryptCreateHash(hAlgorithm, &HashHandle, NULL, NULL, (PUCHAR)p_password.c_str(), p_password.size(), NULL);
	BCryptHashData(HashHandle, (PUCHAR)p_buffer.c_str(), p_buffer.size(), NULL);
	std::vector<UCHAR> hash(HashLength);
	BCryptFinishHash(HashHandle, hash.data(), HashLength, NULL);
	BCryptDestroyHash(HashHandle);
	BCryptCloseAlgorithmProvider(hAlgorithm, 0);
	m_digest = BinToHex(hash);
	return m_digest;
}

wstring
Crypto::Digest(const void* data, const size_t data_size)
{
	AutoCritSec lock(&m_lock);
	BCRYPT_ALG_HANDLE hAlgorithm;
	BCryptOpenAlgorithmProvider(&hAlgorithm, L"MD5", NULL, BCRYPT_HASH_REUSABLE_FLAG);
	UCHAR HashLength;
	ULONG DigestLength;
	BCryptGetProperty(hAlgorithm, L"HashDigestLength", &HashLength, 4, &DigestLength, NULL);
	BCRYPT_HASH_HANDLE HashHandle;
	BCryptCreateHash(hAlgorithm, &HashHandle, NULL, NULL, NULL, NULL, NULL);
	BCryptHashData(HashHandle, (PUCHAR)data, data_size, NULL);
	std::vector<UCHAR> hash(HashLength);
	BCryptFinishHash(HashHandle, hash.data(), HashLength, NULL);
	BCryptDestroyHash(HashHandle);
	BCryptCloseAlgorithmProvider(hAlgorithm, 0);
	m_digest = BinToHex(hash);
	return m_digest;
}

wstring
Crypto::Encryption(wstring p_input, wstring password)
{
	AutoCritSec lock(&m_lock);
	BCRYPT_ALG_HANDLE hAlgorithm;
	BCryptOpenAlgorithmProvider(&hAlgorithm, L"RC4", NULL, BCRYPT_HASH_REUSABLE_FLAG);
	BCRYPT_KEY_HANDLE hKey;
	BCryptGenerateSymmetricKey(hAlgorithm, &hKey, NULL, NULL, (PUCHAR)password.c_str(), password.size(), NULL);
	ULONG cbCipherText;
	BCryptEncrypt(hKey, (PUCHAR)p_input.c_str(), p_input.size(), NULL, NULL, NULL, NULL, NULL, &cbCipherText, NULL);
	std::vector<UCHAR> data;
	data.resize(cbCipherText);
	BCryptEncrypt(hKey, (PUCHAR)p_input.c_str(), p_input.size(), NULL, NULL, NULL, data.data(), cbCipherText, &cbCipherText, NULL);
	BCryptDestroyKey(hKey);
	BCryptCloseAlgorithmProvider(hAlgorithm, 0);
	return Base64Encode(data);
}

wstring
Crypto::Decryption(wstring p_input, wstring password)
{
	AutoCritSec lock(&m_lock);
	std::vector<UCHAR> inputData = Base64Decode(p_input);
	BCRYPT_ALG_HANDLE hAlgorithm;
	BCryptOpenAlgorithmProvider(&hAlgorithm, L"RC4", NULL, BCRYPT_HASH_REUSABLE_FLAG);
	BCRYPT_KEY_HANDLE hKey;
	BCryptGenerateSymmetricKey(hAlgorithm, &hKey, NULL, NULL, (PUCHAR)password.c_str(), password.size(), NULL);
	ULONG cbCipherText;
	BCryptDecrypt(hKey, inputData.data(), inputData.size(), NULL, NULL, NULL, NULL, NULL, &cbCipherText, NULL);
	wstring data;
	data.resize(cbCipherText);
	BCryptDecrypt(hKey, inputData.data(), inputData.size(), NULL, NULL, NULL, (PUCHAR)data.c_str(), cbCipherText, &cbCipherText, NULL);
	BCryptDestroyKey(hKey);
	BCryptCloseAlgorithmProvider(hAlgorithm, 0);
	return data;
}

**Comment by edwig** [comment]
Implemented the BCrypt interface for en- and decryption in the Crypto class. The speed of the fragment above does not comes from BCrypt but from the fact that it uses the much simpler "RC4" encryption method, instead of the the stronger "AES" encryption of the older implementation.
This said: BCrypt has been added as "FastEncryption" and "FastDecryption". Testcases are in the MarlinClient stack.
