### ISSUE TITLE
TestContract.cpp does not compile

### ISSUE THREAD

**Issue by ylaroye** [edwig/Marlin#6]
Current row:
p_message->Reset(m_targetNamespace);

Proposition row:
p_message->Reset(ResponseType::RESP_ACTION_NAME, m_targetNamespace);

**Comment by edwig** [comment]
Dear ylaroye,

 

The Marlin source code compiles just fine.

The master brach compiles in VS 2017

The Marlin_3 branch compiles in VS2015

 

No ResponseType::RESP_ACTION_NAME is known by me.

So please clarify 

1.	what you have done that the source code does not compile in those versions
2.	What is the proposed meaning of the response type in the cryptic code fragment of your email

 

In the hope to learn more from you,

Sincerely,

 

Edwig Huisman

 

Van: ylaroye [mailto:notifications@github.com] 
Verzonden: vrijdag 18 augustus 2017 20:14
Aan: edwig/Marlin <Marlin@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [edwig/Marlin] TestContract.cpp do not compile (#6)

 

Current row:
p_message->Reset(m_targetNamespace);

Proposition row:
p_message->Reset(ResponseType::RESP_ACTION_NAME, m_targetNamespace);

**Comment by edwig** [comment]
AH, Found it.

 

Sorry for the last e-mail.

I missed a push indeed. 

Thank you.

 

Edwig Huisman

 

Van: ylaroye [mailto:notifications@github.com] 
Verzonden: vrijdag 18 augustus 2017 20:14
Aan: edwig/Marlin <Marlin@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [edwig/Marlin] TestContract.cpp do not compile (#6)

 

Current row:
p_message->Reset(m_targetNamespace);

Proposition row:
p_message->Reset(ResponseType::RESP_ACTION_NAME, m_targetNamespace);
